routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\ProductController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\OptionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'root']);

Route::resources([
    'products' => ProductController::class,
    'brands' => BrandController::class,
    'product-categories' => ProductCategoryController::class,
    'options' => OptionController::class,
]);

Route::match(['get', 'post'], '/products/search', [ProductController::class, 'search'])->name('products.search');
Route::post('/products/{product}/toggleFeatured', [ProductController::class, 'toggleFeatured'])->name('products.toggleFeatured');
Route::delete('/products/{productMedia}/removeMedia', [ProductController::class, 'removeMedia'])->name('products.removeMedia');
Route::delete('/products/{productVariant}/removeVariant', [ProductController::class, 'removeVariant'])->name('products.removeVariant');
// Route::post('/products/{product}/clone', [ProductController::class, 'clone'])->name('products.clone');


Route::get('{any}', [App\Http\Controllers\HomeController::class, 'index']);
//Language Translation
Route::get('index/{locale}', [App\Http\Controllers\HomeController::class, 'lang']);
Route::post('/formsubmit', [App\Http\Controllers\HomeController::class, 'FormSubmit'])->name('FormSubmit');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Product extends Model
{
    use HasFactory;
    use Sluggable;

    protected $fillable = [
        'name',
        'sku',
        'slug',
        'price',
        'price_without_tax',
        'brand_id',
        'weight_kg',
        'description',
        'quantity',
        'quantity_low_mark',
        'fixed_shipping_fee',
        'is_free_shipping',
        'page_meta_title',
        'page_meta_description',
        'is_featured',
        'is_active',
        'created_by',
    ];
    
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    /**
     * Get the brand associated with the product.
     */
    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    /**
     * The cateories that belong to the product.
     */
    public function categories()
    {
        return $this->belongsToMany(ProductCategory::class, 'products_product_categories', 'product_id', 'product_category_id');
    }

    /**
     * Get the media for the product.
     */
    public function media()
    {
        return $this->hasMany(ProductMedia::class);
    }

    /**
     * Get the variants for the product.
     */
    public function variants()
    {
        return $this->hasMany(Variant::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductMedia;
use App\Models\Brand;
use App\Models\Variant;
use App\Models\Option;
use App\Models\PriceHistory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Product::paginate(config("app.pagination_size"));
        return view('products.index')->with(compact("data"));
    }

    private function group_assoc($array, $key) {
        $return = array();
        foreach($array as $v) {
            $return[$v[$key]][] = $v;
        }
        return $return;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $data["brands"] = Brand::where('is_active', 1)->orderBy('name')->pluck('name', 'id');
        // $data["options"] = Brand::where('is_active', 1)->orderBy('name')->pluck('name', 'id');
        $data["options"] = Option::where('is_active', 1)->orderBy('name')->get();

        // Group the options value by their name
        $options = $this->group_assoc($data["options"], 'name');

        // dd($request->clone);
        $cloned_product = null;

        if($request->clone) {
            $cloned_product = Product::where('id', $request->clone)->first();

            $cloned_product->name = 'Copy of '. $cloned_product->name;

            $selected = $cloned_product->categories->map(function ($category, $key) {
                return $category->id;
            });
            $cloned_product->categories = $selected->all();


            foreach($cloned_product->variants as $key => $variant) {
                $variant_options = [];
                $variant_options = $variant->options->map(function ($option, $key) {
                    return $option->id;
                });
                $cloned_product->variants[$key]->options = $variant_options->all();
            }
        }

        $data["categories"] = ProductCategory::with('children')->where('is_active', 1)->whereNull('parent_id')->orderBy('name')->get();
        // dd($data["brands"]);
        return view('products.create')->with(compact("data", "options", "cloned_product"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|unique:App\Models\Product|max:2000',
            'sku' => 'required|unique:App\Models\Product|max:50',
            'image_url.*' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'price' => 'required',
            'price_without_tax' => 'required',
            'slug' => 'nullable',
            'brand_id' => 'nullable',
            'weight_kg' => 'required',
            'description' => 'nullable',
            'quantity' => 'required',
            'quantity_low_mark' => 'nullable',
            'fixed_shipping_fee' => 'nullable',
            'is_free_shipping' => 'boolean',
            'page_meta_title' => 'nullable',
            'page_meta_description' => 'nullable',
            'is_featured' => 'boolean',
            'is_active' => 'boolean',
        ]);

        $product = Product::create([
            'name' => $validated["name"],
            'sku' => $validated["sku"],
            'price' => $validated["price"],
            'price_without_tax' => $validated["price_without_tax"],
            'weight_kg' => $validated["weight_kg"],
            'description' => $validated["description"],
            'quantity' => $validated["quantity"],
            'quantity_low_mark' => $validated["quantity_low_mark"],
            'fixed_shipping_fee' => $validated["fixed_shipping_fee"],
            'is_free_shipping' => $validated["is_free_shipping"] ?? false,
            'page_meta_title' => $validated["page_meta_title"],
            'page_meta_description' => $validated["page_meta_description"],
            'is_featured' => $validated["is_featured"] ?? false,
            'is_active' => $validated["is_active"] ?? false,
            'created_by' => Auth::user()->id,
        ]);

        // save images
        $this->saveProductMedia($request, $product->id);

        if($validated["brand_id"]) {
            // add brand
            $brand = Brand::findOrFail($validated["brand_id"]);
            $product->brand()->associate($brand);
            $product->save();
        }

        // add categories
        if(isset($request->categories) && count($request->categories)) {
            // dd($request->categories);
            $product->categories()->attach($request->categories);
        }

        // add variants
        if(isset($request->variant_options) && count($request->variant_options)) {
            // dd($request->variant_options);

            foreach($request->variant_options as $key => $variant_options) {

                $variant_options_arr = explode(",", $variant_options);

                if(!array_filter($variant_options_arr)) {
                    // empty fields
                } else {
                    // create variant
                    $variant = Variant::create([
                        'product_id' => $product->id,
                        'selection_type' => $request->variant_selection_types[$key] ?? '',
                        'color_hex' => $request->variant_color_hexes[$key] ?? null,
                        'price' => $request->variant_prices[$key] ?? null,
                        'is_default' => $request->variant_is_defaults[$key] ?? false,
                        'created_by' => Auth::user()->id,
                    ]);

                    // attach variant options
                    $variant->options()->attach($variant_options_arr);
                }
            }
        }

        return redirect()->route('products.index')->with('status', config("app.success_message"));
    }

    /**
     * Clone a resource in storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function clone(Product $product)
    {
        // create new product
        $new_product = Product::create([
            'name' => 'Copy of ' . $product->name,
            'brand_id' => $product->brand_id,
            'sku' => $product->sku . '_' . uniqid(),
            'price' => $product->price,
            'price_without_tax' => $product->price_without_tax,
            'weight_kg' => $product->weight_kg,
            'description' => $product->description,
            'quantity' => $product->quantity,
            'quantity_low_mark' => $product->quantity_low_mark,
            'fixed_shipping_fee' => $product->fixed_shipping_fee,
            'is_free_shipping' => $product->is_free_shipping,
            'page_meta_title' => $product->page_meta_title,
            'page_meta_description' => $product->page_meta_description,
            'is_featured' => $product->is_featured,
            'is_active' => $product->is_active,
            'created_by' => Auth::user()->id,
        ]);

        // clone images: fetch images and duplicate
        foreach($product->media as $media) {

            $new_image_url = null;

            if($media->media_url) {

                $append_time = '_' . uniqid();
                // str_replace("public/", "storage/", $media->media_url);

                $image_url_arr = explode(".", $media->media_url);
                $extension = array_pop($image_url_arr);
                $tmp_image_url = implode(".", $image_url_arr);

                $new_image_url = $tmp_image_url . $append_time . '.' . $extension;

                // copy image
                if(Storage::disk('public')->exists(str_replace("storage/", "", $media->media_url)) ) {
                    \File::copy($media->media_url, public_path() . "/" . $new_image_url);
                }
            }

            // save media
            $product_media = ProductMedia::create([
                'product_id' => $new_product->id,
                'media_type' => $media->media_type,
                'media_url' => $new_image_url,
                'is_main_image' => $media->is_main_image,
                'created_by' => Auth::user()->id,
            ]);
        }

        $categories = [];
        $categories = $product->categories->map(function ($category, $key) {
            return $category->id;
        });

        // add categories
        if(count($categories)) {
            $new_product->categories()->attach($categories);
        }

        // add variants
        foreach($product->variants as $variant) {
            
            $variant_options = [];
            $variant_options = $variant->options->map(function ($option, $key) {
                return $option->id;
            });

            // create variant
            $new_variant = Variant::create([
                'product_id' => $new_product->id,
                'selection_type' => $variant->selection_type,
                'color_hex' => $variant->color_hex,
                'price' => $variant->price,
                'is_default' => $variant->is_default,
                'created_by' => Auth::user()->id,
            ]);

            // attach variant options
            if(count($variant_options)) {
                $new_variant->options()->attach($variant_options);
            }
        }

        return redirect()->route('products.index')->with('status', config("app.success_message"));
    }

    /**
     * Display the specified resource.
     *

resources/views/products/index.blade.php
@extends('layouts.master')
@section('title')
    @lang('translation.Products')
@endsection
@section('css')
    <!-- Lightbox css -->
    <link href="{{ URL::asset('/assets/libs/magnific-popup/magnific-popup.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
    @component('common-components.breadcrumb')
        @slot('pagetitle') Dashboard @endslot
        @slot('title') @lang('translation.Products') @endslot
    @endcomponent

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <a href="{{ route('products.create') }}"  class="btn btn-success waves-effect waves-light">
                                    <i class="mdi mdi-plus me-2"></i> Add New
                                </a>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-inline float-md-end mb-3">
                                <div class="search-box ms-2">
                                    <div class="position-relative">
                                        <input type="text" class="form-control rounded bg-light border-0"
                                            placeholder="Search...">
                                        <i class="mdi mdi-magnify search-icon"></i>
                                    </div>
                                </div>

                            </div>
                        </div>


                    </div>
                    <!-- end row -->
                    <div class="table-responsive mb-4">
                        <table class="table table-centered table-nowrap mb-0">
                            <thead>
                                <tr>
                                    <th scope="col" style="width: 50px;">
                                        <div class="form-check font-size-16">
                                            <input type="checkbox" class="form-check-input" id="contacusercheck">
                                            <label class="form-check-label" for="contacusercheck"></label>
                                        </div>
                                    </th>
                                    <th scope="col">Name</th>
                                    <th scope="col">SKU</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Active?</th>
                                    <th scope="col">Featured</th>
                                    <th scope="col" style="width: 200px;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $item)
                                <tr>
                                    <th scope="row">
                                        <div class="form-check font-size-16">
                                            <input type="checkbox" class="form-check-input" id="contacusercheck1">
                                            <label class="form-check-label" for="contacusercheck1"></label>
                                        </div>
                                    </th>
                                    <td>
                                        @if(count($item->media))
                                        <a class="image-popup-vertical-fit" href="{{ Misc::ImageURL($item->media->first()->media_url) }}" title="{{ $item->name }}">
                                        <img src="{{ Misc::ImageURL($item->media->first()->media_url) }}" alt=""
                                            class="avatar-xs rounded-circle me-2"></a>
                                        @endif
                                        <a href="#" class="text-body">{{ $item->name }}</a>
                                    </td>
                                    <td>{{ $item->sku }}</td>
                                    <td>{{ $item->quantity }}</td>
                                    <td>N{{ $item->price }}</td>
                                    <td>
                                        <div class="badge bg-soft-{{ $item->is_active ? 'success' : 'danger' }} font-size-12">{{ $item->is_active ? 'YES' : 'NO' }}</div>
                                    </td>
                                    <td>
                                        <a title="{{ $item->is_featured ? 'Remove' : 'Set' }} Featured Product?" href="{{ route('products.toggleFeatured', $item->id) }}" class="px-2 text-{{ $item->is_featured ? 'success' : 'danger' }}" 
                                            onclick="event.preventDefault(); if(confirm('Are you you want to do this?')) 
                                            document.getElementById('toggle-featured-{{ $item->id }}').submit();">

                                            <i class="uil uil-{{ $item->is_featured ? 'bolt' : 'bolt-slash' }} font-size-18"></i>
                                        </a>
                                        <form id="toggle-featured-{{ $item->id }}" action="{{ route('products.toggleFeatured', $item->id) }}" method="POST">
                                            @csrf
                                        </form>
                                    </td>
                                    <td>
                                        <ul class="list-inline mb-0">
                                            <li class="list-inline-item">
                                                <a href="{{ route('products.edit', ['product' => $item]) }}" class="px-2 text-primary"><i
                                                        class="uil uil-pen font-size-18"></i></a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a href="{{ route('products.create', ['clone' => $item]) }}" class="px-2 text-primary"><i
                                                        class="uil uil-copy font-size-18"></i></a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a href="{{ route('products.destroy', $item->id) }}" class="px-2 text-danger" onclick="event.preventDefault();
                                                if(confirm('Are you sure you want to do this?')) document.getElementById('delete-form-{{ $item->id }}').submit();">
                                                    <i class="uil uil-trash-alt font-size-18"></i>
                                                </a>
                                                <form id="delete-form-{{ $item->id }}" action="{{ route('products.destroy', $item->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                            </li>
                                            <!-- <li class="list-inline-item dropdown">
                                                <a class="text-muted dropdown-toggle font-size-18 px-2" href="#"
                                                    role="button" data-bs-toggle="dropdown" aria-haspopup="true">
                                                    <i class="uil uil-ellipsis-v"></i>
                                                </a>

                                                <div class="dropdown-menu dropdown-menu-end">
                                                    <a class="dropdown-item" href="{{ route('products.create', $item->id) }}" onclick="event.preventDefault();
                                                    if(confirm('Are you sure you want to do this?')) document.getElementById('clone-form-{{ $item->id }}').submit();">Clone</a>

                                                    <form id="clone-form-{{ $item->id }}" action="{{ route('products.create', $item->id) }}" method="POST">
                                                        @csrf
                                                    </form>
                                                </div>
                                            </li> -->
                                        </ul>
                                    </td>
                                </tr>
                                @endforeach

                                <!-- <tr>
                                    <th scope="row">
                                        <div class="form-check font-size-16">
                                            <input type="checkbox" class="form-check-input" id="contacusercheck1">
                                            <label class="form-check-label" for="contacusercheck1"></label>
                                        </div>
                                    </th>
                                    <td>
                                        <a class="image-popup-vertical-fit" href="{{ URL::asset('/assets/images/users/avatar-2.jpg') }}" title="Nike">
                                        <img src="{{ URL::asset('/assets/images/users/avatar-2.jpg') }}" alt=""
                                            class="avatar-xs rounded-circle me-2"></a>
                                        <a href="#" class="text-body">Nike</a>
                                    </td>
                                    <td>Full Stack Developer</td>
                                    <td>
                                        <div class="badge bg-soft-danger font-size-12">NO</div>
                                    </td>
                                    <td>
                                        <ul class="list-inline mb-0">
                                            <li class="list-inline-item">
                                                <a href="javascript:void(0);" class="px-2 text-primary"><i
                                                        class="uil uil-pen font-size-18"></i></a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a href="javascript:void(0);" class="px-2 text-danger"><i
                                                        class="uil uil-trash-alt font-size-18"></i></a>
                                            </li>
                                        </ul>
                                    </td>
                                </tr> -->

                            </tbody>
                        </table>
                    </div>
                    <div class="row mt-4">
                        <div class="col-sm-6">
                            <div>
                                <p class="mb-sm-0">Showing {{ $data->firstItem() }} to {{ $data->lastItem() }} of {{ $data->total() }} entries</p>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="float-sm-end">
                                <!-- <ul class="pagination mb-sm-0">
                                    <li class="page-item disabled">
                                        <a href="#" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link">1</a>
                                    </li>
                                    <li class="page-item active">
                                        <a href="#" class="page-link">2</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link">3</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link"><i class="mdi mdi-chevron-right"></i></a>
                                    </li>
                                </ul> -->
                                {{ $data->onEachSide(2)->links() }}
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
    <!-- end row -->

@endsection
@section('script')
    <script src="{{ URL::asset('/assets/libs/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <!-- Magnific Popup-->
    <script src="{{ URL::asset('/assets/libs/magnific-popup/magnific-popup.min.js') }}"></script>
    <!-- lightbox init js-->
    <script src="{{ URL::asset('/assets/js/pages/lightbox.init.js') }}"></script>
@endsection